## DNS part - wildcard DNS
address=/vmtest.cluster.lan/192.168.171.201
address=/k8s.vmtest.cluster.lan/192.168.171.200



# MORE LOGGING - If you need it
#log-dhcp

# This defines a bunch of tags. Use them in your dhcp-host directives / as a tag in OpenWRT LuCi.
# tinkpxelinuxt6: u-boot/PXELinux.cfg
# tinkuefix86pxet6: UEFI for x86
# tinkuefiarm64pxet6: UEFI for arm64
# tinkrpit6: RPi native EEPROM firmware

## On NanoPC T6 - with k3s; TFTP is at 192.168.66.171

# Create a tag for DHCP clients that announce themselves as Tinkerbell (namely: Tinkerbell's build of iPXE)
dhcp-match=tinkerbell, option:user-class, Tinkerbell

# For u-boot pxelinux.cfg clients:
dhcp-boot=tag:tinkpxelinuxt6,tinkpxelinux-not-really-used-T6.conf,none,192.168.66.171

# For x86 UEFI clients: (first is for UEFI PXE -> 2nd is for Tinkerbell's iPXE)
dhcp-boot=tag:tinkuefix86pxet6,tag:!tinkerbell,ipxe.efi,192.168.66.171,192.168.66.171
dhcp-boot=tag:tinkuefix86pxet6,tag:tinkerbell,http://192.168.66.171:7171/ipxe/script/auto.ipxe

# For arm64 UEFI clients: (first is for UEFI PXE -> 2nd is for Tinkerbell's iPXE)
dhcp-boot=tag:tinkuefiarm64pxet6,tag:!tinkerbell,snp-arm64.efi,192.168.66.171,192.168.66.171
dhcp-boot=tag:tinkuefiarm64pxet6,tag:tinkerbell,http://192.168.66.171:7171/ipxe/script/auto.ipxe

# For RaspberryPi (4b, at least) native EEPROM firmware booting (use it to chainload u-boot and pxelinux.cfg)
#                                Extra options for server-ip-address and tftp-server are required
#                                *Never* try to replace it with pxe-service= directive, as that breaks the others
dhcp-boot=tag:tinkrpit6,tinkrpi6,,192.168.66.171
dhcp-option=tag:tinkrpit6,option:server-ip-address,192.168.66.171
dhcp-option=tag:tinkrpit6,option:tftp-server,"192.168.66.171"
