# MORE LOGGING
log-dhcp



# -M, --dhcp-boot=[tag:<tag>,]<filename>,[<servername>[,<server address>|<tftp_servername>]]
# (IPv4 only) Set BOOTP options to be returned by the DHCP server. 
# Server name and address are optional: if not provided, the name is left empty, and the address set to the address of the machine running dnsmasq. 
# If dnsmasq is providing a TFTP service (see --enable-tftp ) then only the filename is required here to enable network booting. 
# If the optional tag(s) are given, they must match for this configuration to be sent. 
# Instead of an IP address, the TFTP server address can be given as a domain name which is looked up in /etc/hosts. 
#  This name can be associated in /etc/hosts with multiple IP addresses, which are used round-robin. This facility can be used to load balance the tftp load among a set of servers.

# Always
dhcp-match=tinkerbell, option:user-class, Tinkerbell

# On CM3588 - vmtest cluster
dhcp-boot=tag:tinkpxelinux,tinkpxelinux-not-really-used-CM3588.conf,none,192.168.66.171
dhcp-boot=tag:tinkuefipxe,tag:!tinkerbell,ipxe.efi,none,192.168.66.170
dhcp-boot=tag:tinkuefipxe,tag:tinkerbell,http://192.168.66.170:7171/ipxe/script/auto.ipxe
dhcp-boot=tag:tinkuefiarm64pxe,tag:!tinkerbell,snp-arm64.efi,none,192.168.66.170
dhcp-boot=tag:tinkuefiarm64pxe,tag:tinkerbell,http://192.168.66.170:7171/ipxe/script/auto.ipxe

# On NanoPC T6 - with k3s
dhcp-boot=tag:tinkpxelinuxt6,tinkpxelinux-not-really-used-T6.conf,none,192.168.66.171
dhcp-boot=tag:tinkuefix86pxet6,tag:!tinkerbell,ipxe.efi,none,192.168.66.171
dhcp-boot=tag:tinkuefix86pxet6,tag:tinkerbell,http://192.168.66.171:7171/ipxe/script/auto.ipxe
dhcp-boot=tag:tinkuefiarm64pxet6,tag:!tinkerbell,snp-arm64.efi,none,192.168.66.171
dhcp-boot=tag:tinkuefiarm64pxet6,tag:tinkerbell,http://192.168.66.171:7171/ipxe/script/auto.ipxe

dhcp-boot=tag:tinkrpit6,tinkrpi6,,192.168.66.171

pxe-service=tag:tinkrpit6,0,"Raspberry Pi Boot",tinkrpi6,192.168.66.171


# snp-arm64.efi is for arm64
# ipxe.efi is for amd64




#dhcp-boot=tag:tinkuefipxe,ipxe.efi,192.168.66.170,192.168.66.170
#dhcp-boot=tag:tinkuefipxe,http://192.168.66.170:7171/ipxe/script/auto.ipxe



# Change the following lines if you want dnsmasq to serve SRV
# records.
# You may add multiple srv-host lines.
# The fields are <name>,<target>,<port>,<priority>,<weight>

# A SRV record sending LDAP for the example.com domain to
# ldapserver.example.com port 289
#srv-host=_ldap._tcp.example.com,ldapserver.example.com,389

# Two SRV records for LDAP, each with different priorities
#srv-host=_ldap._tcp.example.com,ldapserver.example.com,389,1
#srv-host=_ldap._tcp.example.com,ldapserver.example.com,389,2

# A SRV record indicating that there is no LDAP server for the domain
# example.com
#srv-host=_ldap._tcp.example.com

# The following line shows how to make dnsmasq serve an arbitrary PTR
# record. This is useful for DNS-SD.
# The fields are <name>,<target>
#ptr-record=_http._tcp.dns-sd-services,"New Employee Page._http._tcp.dns-sd-services"

# Change the following lines to enable dnsmasq to serve TXT records.
# These are used for things like SPF and zeroconf.
# The fields are <name>,<text>,<text>...

#Example SPF.
#txt-record=example.com,"v=spf1 a -all"

#Example zeroconf
#txt-record=_http._tcp.example.com,name=value,paper=A4

# Provide an alias for a "local" DNS name. Note that this _only_ works
# for targets which are names from DHCP or /etc/hosts. Give host
# "bert" another name, bertrand
# The fields are <cname>,<target>
#cname=bertand,bert
