password zebra
log syslog
access-list vty permit 127.0.0.0/8
access-list vty deny any
line vty
 access-class vty

frr defaults traditional
hostname OpenWrt-R5S

# 65000 here, 65000 on the nodes == iBGP
router bgp 65000
 bgp router-id 192.168.66.1
 no bgp ebgp-requires-policy

 # create a peer-group for all dynamic iBGP neighbors
 neighbor NODEPEERS peer-group
 neighbor NODEPEERS remote-as 65000
 neighbor NODEPEERS next-hop-self # unsure about this

 # reduce BGP timers (keepalive / hold)
 timers bgp 3 9

 # activate IPv4 unicast for the peer-group
 address-family ipv4 unicast
  neighbor NODEPEERS activate
 exit-address-family

 # allow dynamic neighbors from the 0.0/16 subnet
 #bgp listen range 192.168.66.0/24 peer-group NODEPEERS
 bgp listen range 192.168.0.0/16 peer-group NODEPEERS
